language: java
jdk:
- openjdk11
addons:
  apt:
    packages:
    - docker-ce
before_install:
- docker login --username=innulicc@gmail.com --password=69dc5a88-95c2-4ab2-8314-e8069c162c14 registry.heroku.com
script:
- "./gradlew test build"
after_success:
- heroku container:push web -a brain-heap
- heroku container:release web -a brain-heap
after_failure:
- cat target/surefire-reports/*.txt
notifications:
  slack: neueda-technologies:ZYh2b6u5OcMbhwMu6i9U47fQ
  email:
    recipients:
    - innulic@mail.ru
    - a.a.zarubina@gmail.com
    - aflammaal@gmail.com
    on_success: change
    on_failure: always
