language: java
jdk:
- openjdk11
services:
- docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
addons:
  apt:
    packages:
    - docker-ce
script:
- "./gradlew test build"
after_success:
- docker build -t innulic/brain-heap .
- docker images
- docker push innulic/brain-heap:latest
after_failure:
- cat target/surefire-reports/*.txt
deploy:
  provider: heroku
  app: brain-heap
  on:
    repo: innulic/brainheap-back
  api_key:
    secure: RfUsZ3P9506K5vfmnNeg4DlrAFrHEHCGm4Iyrm9LlYcJamXAT1/DxqzCQaXYE/u5xJiYNkCMS7BUImYu9ao0E6F6kymm6LyiS9vXWaUM/lxc8Ll7feLs1PGHwWUlqoCb/XEj7oBEPJjaCSVu7VZZDPStl2YiRNWa/TPdROeQWvzJUHzKAin2NH+yIgzETyypl0NIqPhrK26WmE3zecg+fsb5QN9XJZWca5gtRBdTLBkOsUcC5X3HAO78bGFXR1iZ8S+VzGJ5O+kHDsADXuKIAChMg5VIABtYPsg5H72NopOeTCISadrUPaLQAm6+HZjARYkH7g+2vMYyc3MKzPtwJ005OzFzyhEclIKlpTmGNgQaL0OE4CrZEvAtvOW9q1B3KfwgIUHLrhCbuupf2ISa0T820cNZ1E8YDt+6+DwUJ7nEft9anDpneY83a9nBHFrcpY+3M3X1iezqSA1wJSrgtSLZmSiX7XWoCAlF4rIEB6nQ/peZkSD04H7sY38tCLA21Mr/p2sBmtG2dom35FCft/bW1R5E5A9QhIDZI2kjKb/Yi6qZkc3rDIelrQ9GhZ/GBpnrz1pgG2fNK0h8aoGlKU7FFK8IFxGKSCKZKbpomrSzSjpBrb0AEk/cgur9wqBSdzhjUKV2Owd95hzpJipMIQCjTnyNxVNhDxp/4XOOFqA=
notifications:
  slack: neueda-technologies:ZYh2b6u5OcMbhwMu6i9U47fQ
  email:
    recipients:
    - innulic@mail.ru
    - a.a.zarubina@gmail.com
    - aflammaal@gmail.com
    on_success: change
    on_failure: always
env:
  matrix:
    secure: ZVH548F0B99Jz7u/7zdIACoaS/bAC04ZL38lsC7zVMdsEbQ0F9pIUXfjqnF2ZNehDSzKyWyYyE2wS652/G9jUrTVUXpRxHpsc1hrWDJH9uNSYvxlbeWCJNyWAhMvvLxH5pbmrNMOIcu+n5K0vsy/FejxgcQFp/LoYy8dWtRRxGAKcN5Zf46OVnVyUzmMNn1cogxHCxspYUBatAv10R71p1Qr32qddSr2ocbp3+HvuQe8me1CoBzCMwho75ZOe60Tx9iDH/7MXQY7IdyF6QHJ19tw+qDfSu26og83sehp3qOQvJf7CGcM532XWZYfjjb53lQtczoOZACN4WuuAgVbeGG1QlMhHfftip1Ut3YYS3TQg3LAtvfFFXarTD5n702RfvEAi2cRjgxX8NKrrQmnJBRUFr8FShQ5fmNo8/0V6xxxmoaoYBp07Fg20tVQLBfnsF5T/ckclHWdPoAu64bBiLpO73Tu5teI0ifnHtK2ysYnCNrK3Y0sqn1kqGcQMRbg+01WBX8mX+ePuDFYRR2svc/dnOPmvGTF4ojA7qQnHq59WyHYvg+M0RLCP+Xz5PYHsJOKUE+6pLtRDiyFrYr8yegsGpVaLhPAdR6p23cQmxTfGyi3b6n5Y8Bw2IR6orR1N/l31DQ8/AxkTzUs0Av7yq6U7bVRbJ5zCxuUMEcKbUI=
