language: java
jdk:
- openjdk11
addons:
  apt:
    packages:
    - docker-ce
script:
- "./gradlew test build"
after_success:
after_failure:
- cat target/surefire-reports/*.txt
notifications:
  slack: neueda-technologies:ZYh2b6u5OcMbhwMu6i9U47fQ
  email:
    recipients:
    - innulic@mail.ru
    - a.a.zarubina@gmail.com
    - aflammaal@gmail.com
    on_success: change
    on_failure: always
