language: java
jdk:
  - openjdk11
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - ./gradlew test build
services:
  - docker
notifications:
  slack:
    on_success: change
    on_failure: always
  email:
    recipients:
      - innulic@mail.ru
      - a.a.zarubina@gmail.com
      - aflammaal@gmail.com
    on_success: change
    on_failure: always
after_success:
  - docker build -t kgb/brainheap-back .
  - docker images
  - docker push innulic/brain-heap
after_failure:
addons:
  apt:
    packages:
      - docker-ce