# Init configuration
language: java
jdk:
  - openjdk11
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
addons:
  apt:
    packages:
      - docker-ce
# Build phase
script:
  - ./gradlew test build
after_success:
  - docker build -t innulic/brain-heap .
  - docker images
  - docker push innulic/brain-heap:latest
after_failure:
  - cat target/surefire-reports/*.txt
# Deploy part
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
  app:
    master: brainheap-staging
# Setup notification
notifications:
  slack: neueda-technologies:ZYh2b6u5OcMbhwMu6i9U47fQ
    on_success: change
    on_failure: always
  email:
    recipients:
      - innulic@mail.ru
      - a.a.zarubina@gmail.com
      - aflammaal@gmail.com
    on_success: change
    on_failure: always