version: '3.4'
services:
  brainheap-back:
# todo(innulic) move to specific version
    image: akisali/brainheap:latest
    container_name: "brainheap-back"
    ports:
      - 8080:8080
    links:
      - brainheap-mongodb
    depends_on:
      - brainheap-mongodb
  brainheap-mongodb:
    build: db
    container_name: "brainheap-mongodb"
    environment:
    - MONGO_SERVER=brainheap-db
    - MONGO_PORT=27017
    - MONGO_DB=brainheap
    - MONGO_DB_STARTER=brainheap_db_starter
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017