version: '3.3'
services:
  brainheap-back:
    # todo(innulic) move to specific version
    image: akisali/brainheap:latest
    container_name: "brainheap-back"
    ports:
      - 8080:8080
    links:
      - brainheap-mongodb
    depends_on:
      - brainheap-mongodb
  brainheap-mongodb:
    image: mongo:3.6
    container_name: "brainheap-mongodb"
    environment:
      - MONGO_INITDB_DATABASE=brainheap
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017