server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://brainheap-mongodb/brainheap
      port: 27017
  security:
    oauth2:
      client:
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
        registration:
          facebook:
            provider: facebook
            clientId: 418386422290943
            clientSecret: 3f23692b595de4ffe1d52e36b1daf069
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile